auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 5
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title: 韦海生博客
url: https://www.weihaisheng.com/
feed: /atom.xml
author_info: <a href="/">weihaisheng</a>

theme: jekyll-theme-cayman
