auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title: 韦海生博客
url: http://www.weihaisheng.com
feed: /atom.xml
author_info: <a href="http://www.weihaisheng.com/">weihaisheng</a>

theme: jekyll-theme-cayman

paginate:5
paginate_path: "page:num"
